### ISSUE TITLE
NPM publish?

### ISSUE THREAD

**Issue by fstanis** [jonathantneal/posthtml-inline-assets#11]
Hi, I can see that version 3.0.0 has been released a month ago, but the NPM latest is still 2.0.0.

Any plans to publish 3.0.0 to NPM?

**Comment by gpoole** [comment]
+1: @jonathantneal could you publish the latest version please? The configurable transforms look very useful!

**Comment by jonathantneal** [comment]
Published as 3.0.0. Thanks!
