### ISSUE TITLE
Nothing Works As Expected, Crashes and Generates Incorrect Output

### ISSUE THREAD

**Issue by dwighthouse** [jonathantneal/posthtml-inline-assets#3]
I've yet to get this script to work at all. No combination of options appears to result in the correct output. There are numerous problems with all options, it seems.

Here's my test.

There is a simple HTML page, named `test.html`, located in the root of the project:

``` html
<!doctype html>
<meta charset="utf-8">
<title>Test</title>

<!-- Multiple references to try and find one path scheme that will work. -->
<script src="./test.js"></script>
<script src="/test.js"></script>
<script src="test.js"></script>
```

There is a simple JS script, named `test.js`, located in the root of the project:

``` javascript
(function() {
    console.log('test');
}());
```

Using gulp, posthtml, and posthtml-inline-assets, a simple build process will look like this, effectively identical to that described in the `README.md` file:

``` javascript
var gulp = require('gulp');
var posthtml = require('gulp-posthtml');
var inlineSrc = require('posthtml-inline-assets');

gulp.task('test', function() {
    return gulp.src('./test.html')
        .pipe(posthtml([
            inlineSrc()
        ]))
        .pipe(gulp.dest('./test'))
});
```

---

If the `test` gulp task is run, the resulting file at `./test/test.html` will replace all three script tags with the inlined [contents of `test.js` from the `posthtml-inline-assets` repository](https://github.com/jonathantneal/posthtml-inline-assets/blob/master/test.js)! This is completely wrong. Generating no output at all would be better than injecting a file from a completely different project.

---

What if the script name doesn't match the name of a script in the `posthtml-inline-assets` repository? Changing each reference from `test.js` to `test1.js` in the HTML, as well as the filename, the result is that the stream crashes silently, no file is generated, no error is displayed.

This also happens if an empty object is given to `inlineSrc`, like so: `inlineSrc({})`.

---

What if the `from` option is specified to point to the top-level directory where both `test.html` and `test1.js` can be found? The stream crashes silently, no file is generated, no error is displayed.

---

What if the `inline` option object is also specified, so that the scripts are told to inline, but images and styles are told not to inline (my use case)? The options would look like this:

``` javascript
{
    from: './',
    inline: {
        script: true,
        style: false,
        image: false
    }
}
```

If these options are used, an output file is generated, but none of the script tags have been inlined.

---

What if I attempt to do it myself by creating my own `check` and `then` function callbacks for the script option, something like this:

``` javascript
{
    from: './',
    inline: {
        script: {
            check: function (node) {
                if (node.tag === 'script')
                {
                    console.log(node.attrs.src);
                }
                return node.tag === 'script' && node.attrs && node.attrs.src;
            },
            then: function (node, data) {
                console.log(data);
            }
        },
        style: false,
        image: false
    }
}
```

Bafflingly, while the check does correctly log the src attribute of each script tag, the `then` function is never called. Also, the stream crashes silently, no file is generated, no error is displayed. This happens even if I inject exactly the same code from the source code in as my own custom `check`/`then` callback combination.

---

What if the `inline` boolean options are specified, but the `from` option is not specified, like so:

``` javascript
{
    inline: {
        script: true,
        style: false,
        image: false
    }
}
```

If these options are used, an output file is generated, but none of the script tags have been inlined.

---

Am I crazy? I must be missing something simple here, right? I've tried to follow the instructions in the README as described, and I've looked through the source code and test files for examples of how to use this. Yet, nothing appears to work.

Even if I am doing something wrong, it is troubling that my incorrect usage of the plugin could crash the stream at all, let alone with no warnings or errors displayed to explain what went wrong.

What's going on?

```
Node v4.1.2
"gulp": "^3.9.1",
"gulp-posthtml": "^1.5.2",
"posthtml-inline-assets": "^1.0.2",
```

**Comment by jonathantneal** [comment]
I think I figured out where most of your issues were coming from and I’ve released a new version.
